### ISSUE TITLE
Better type checking for sample statements

### ISSUE THREAD

**Issue by joewing** [cibotech/ScalaStan#48]
Right now it's possible to generate invalid Stan code using `~`.  For example:
```scala
        val x = data(real())
        val model = new Model {
          x ~ stan.poisson(1.0)
        }
```
The Stan for this will not compile because `x` is `real`.  Changing `x` to `int` fixes the problem.  ScalaStan should identify this before generating Stan code (ideally at Scala compile time).

**Comment by joewing** [comment]
I believe this is addressed with #53.

**Comment by vrao85** [comment]
Hi - I'm getting an invlaid sample statement error from this:
```scala
omega ~ stan.lkj_corr(2)
```
Previously I declared omega as follows:
```
  val omega = parameter(corrMatrix(assetCount))
```
Was PR #53 supposed to have addressed this?

**Comment by joewing** [comment]
The `lkj_corr` distribution provides a slight complication for the type checking in ScalaStan related to the size of matrix in that it's not known when the distribution is created.  To work around it, there is a second version of the distribution that takes two arguments, where the first argument is the size of the matrix.  So I think the following should do what you want:

```scala
  val omega = parameter(corrMatrix(5))
  omega ~ stan.lkj_corr(5, 2)
```

That is something that should be fixed though. I'll file an issue for it.
